version: '3.7'

services:
  api:
    image: eiximenis/s2020-api
    build:
      args:
        nv: 15
      context: api
      dockerfile: Dockerfile
  web:
    image: eiximenis/s2020-web
    build:
      context: BeersWeb
      dockerfile: Dockerfile